from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QGroupBox, QLabel,
    QPushButton, QSizePolicy, QStackedWidget, QWidget)

import resource_rc

class Ui_bookdetails1(object):
    def setupUi(self, bookdetails1):
        if not bookdetails1.objectName():
            bookdetails1.setObjectName(u"bookdetails1")
        bookdetails1.resize(689, 442)
        bookdetails1.setStyleSheet(u"background-color: rgb(85, 0, 127);\n"
"font: 9pt \"Arial Rounded MT Bold\";")
        self.stackedWidget: QStackedWidget = self.findChild(QStackedWidget, 'stackedWidget')
        self.stackedWidget = QStackedWidget(bookdetails1)
        self.stackedWidget.setObjectName(u"stackedWidget")
        self.stackedWidget.setGeometry(QRect(10, 10, 671, 421))
        self.stackedWidget.setStyleSheet(u"background-color: rgb(170, 85, 255);")
        self.stackedWidgetPage1 = QWidget()
        self.stackedWidgetPage1.setObjectName(u"stackedWidgetPage1")
        self.groupBox = QGroupBox(self.stackedWidgetPage1)
        self.groupBox.setObjectName(u"groupBox")
        self.groupBox.setGeometry(QRect(10, 10, 651, 401))
        self.widget = QWidget(self.groupBox)
        self.widget.setObjectName(u"widget")
        self.widget.setGeometry(QRect(10, 20, 151, 171))
        self.widget.setAutoFillBackground(False)
        self.widget.setStyleSheet(u"image: url(:/pics/files/coverpage/b201806081528456308.jpg);\n"
"")
        self.label_2 = QLabel(self.groupBox)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(20, 210, 141, 21))
        self.pushButton = QPushButton(self.groupBox)
        self.pushButton.setObjectName(u"pushButton")
        self.pushButton.setGeometry(QRect(250, 190, 381, 41))
        self.pushButton.setStyleSheet(u"background-color: rgb(85, 0, 127);\n"
"")
        icon = QIcon()
        icon.addFile(u":/pics/files/001-shopping-cart.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButton.setIcon(icon)
        self.label = QLabel(self.groupBox)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(250, 40, 241, 21))
        self.label.setStyleSheet(u"")
        self.label_3 = QLabel(self.groupBox)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(250, 80, 131, 21))
        self.label_3.setStyleSheet(u"")
        self.label_4 = QLabel(self.groupBox)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(250, 110, 251, 21))
        self.label_4.setStyleSheet(u"")
        self.label_5 = QLabel(self.groupBox)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(250, 140, 111, 31))
        self.label_5.setStyleSheet(u"")
        self.label_6 = QLabel(self.groupBox)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(20, 270, 591, 41))
        self.label_6.setStyleSheet(u"")
        self.pushButton_15 = QPushButton(self.groupBox)
        self.pushButton_15.setObjectName(u"pushButton_15")
        self.pushButton_15.setGeometry(QRect(550, 370, 80, 20))
        self.stackedWidget.addWidget(self.stackedWidgetPage1)
        self.page = QWidget()
        self.page.setObjectName(u"page")
        self.groupBox_2 = QGroupBox(self.page)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.groupBox_2.setGeometry(QRect(10, 10, 651, 401))
        self.widget_2 = QWidget(self.groupBox_2)
        self.widget_2.setObjectName(u"widget_2")
        self.widget_2.setGeometry(QRect(10, 20, 151, 171))
        self.widget_2.setAutoFillBackground(False)
        self.widget_2.setStyleSheet(u"image: url(:/pics/files/coverpage/'Batman 251 by Neal Adams' Poster by DC Comics _ Displate - Copy.jpg);\n"
"")
        self.label_7 = QLabel(self.groupBox_2)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(20, 210, 141, 21))
        self.pushButton_2 = QPushButton(self.groupBox_2)
        self.pushButton_2.setObjectName(u"pushButton_2")
        self.pushButton_2.setGeometry(QRect(250, 190, 381, 41))
        self.pushButton_2.setStyleSheet(u"background-color: rgb(85, 0, 127);\n"
"")
        self.pushButton_2.setIcon(icon)
        self.label_8 = QLabel(self.groupBox_2)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(250, 40, 161, 21))
        self.label_8.setStyleSheet(u"")
        self.label_9 = QLabel(self.groupBox_2)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(250, 80, 181, 21))
        self.label_9.setStyleSheet(u"")
        self.label_10 = QLabel(self.groupBox_2)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(250, 110, 251, 21))
        self.label_10.setStyleSheet(u"")
        self.label_11 = QLabel(self.groupBox_2)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(250, 140, 111, 31))
        self.label_11.setStyleSheet(u"")
        self.label_12 = QLabel(self.groupBox_2)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(20, 270, 591, 41))
        self.label_12.setStyleSheet(u"")
        self.pushButton_16 = QPushButton(self.groupBox_2)
        self.pushButton_16.setObjectName(u"pushButton_16")
        self.pushButton_16.setGeometry(QRect(550, 370, 80, 20))
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.groupBox_3 = QGroupBox(self.page_2)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.groupBox_3.setGeometry(QRect(10, 0, 651, 401))
        self.widget_3 = QWidget(self.groupBox_3)
        self.widget_3.setObjectName(u"widget_3")
        self.widget_3.setGeometry(QRect(10, 20, 151, 171))
        self.widget_3.setAutoFillBackground(False)
        self.widget_3.setStyleSheet(u"image:url(:/pics/files/coverpage/9781472260086.jpg)")
        self.label_13 = QLabel(self.groupBox_3)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(20, 210, 141, 21))
        self.pushButton_3 = QPushButton(self.groupBox_3)
        self.pushButton_3.setObjectName(u"pushButton_3")
        self.pushButton_3.setGeometry(QRect(250, 190, 381, 41))
        self.pushButton_3.setStyleSheet(u"background-color: rgb(85, 0, 127);\n"
"")
        self.pushButton_3.setIcon(icon)
        self.label_14 = QLabel(self.groupBox_3)
        self.label_14.setObjectName(u"label_14")
        self.label_14.setGeometry(QRect(250, 40, 241, 21))
        self.label_14.setStyleSheet(u"")
        self.label_15 = QLabel(self.groupBox_3)
        self.label_15.setObjectName(u"label_15")
        self.label_15.setGeometry(QRect(250, 80, 131, 21))
        self.label_15.setStyleSheet(u"")
        self.label_16 = QLabel(self.groupBox_3)
        self.label_16.setObjectName(u"label_16")
        self.label_16.setGeometry(QRect(250, 110, 251, 21))
        self.label_16.setStyleSheet(u"")
        self.label_17 = QLabel(self.groupBox_3)
        self.label_17.setObjectName(u"label_17")
        self.label_17.setGeometry(QRect(250, 140, 111, 31))
        self.label_17.setStyleSheet(u"")
        self.label_18 = QLabel(self.groupBox_3)
        self.label_18.setObjectName(u"label_18")
        self.label_18.setGeometry(QRect(20, 270, 591, 41))
        self.label_18.setStyleSheet(u"")
        self.pushButton_17 = QPushButton(self.groupBox_3)
        self.pushButton_17.setObjectName(u"pushButton_17")
        self.pushButton_17.setGeometry(QRect(550, 370, 80, 20))
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.groupBox_4 = QGroupBox(self.page_3)
        self.groupBox_4.setObjectName(u"groupBox_4")
        self.groupBox_4.setGeometry(QRect(10, 10, 651, 401))
        self.widget_4 = QWidget(self.groupBox_4)
        self.widget_4.setObjectName(u"widget_4")
        self.widget_4.setGeometry(QRect(10, 20, 151, 171))
        self.widget_4.setAutoFillBackground(False)
        self.widget_4.setStyleSheet(u"\n"
"image: url(:/pics/files/coverpage/Atomic Habits.jpg);\n"
"")
        self.label_19 = QLabel(self.groupBox_4)
        self.label_19.setObjectName(u"label_19")
        self.label_19.setGeometry(QRect(20, 210, 141, 21))
        self.pushButton_4 = QPushButton(self.groupBox_4)
        self.pushButton_4.setObjectName(u"pushButton_4")
        self.pushButton_4.setGeometry(QRect(250, 190, 381, 41))
        self.pushButton_4.setStyleSheet(u"background-color: rgb(85, 0, 127);\n"
"")
        self.pushButton_4.setIcon(icon)
        self.label_20 = QLabel(self.groupBox_4)
        self.label_20.setObjectName(u"label_20")
        self.label_20.setGeometry(QRect(250, 40, 241, 21))
        self.label_20.setStyleSheet(u"")
        self.label_21 = QLabel(self.groupBox_4)
        self.label_21.setObjectName(u"label_21")
        self.label_21.setGeometry(QRect(250, 80, 131, 21))
        self.label_21.setStyleSheet(u"")
        self.label_22 = QLabel(self.groupBox_4)
        self.label_22.setObjectName(u"label_22")
        self.label_22.setGeometry(QRect(250, 110, 251, 21))
        self.label_22.setStyleSheet(u"")
        self.label_23 = QLabel(self.groupBox_4)
        self.label_23.setObjectName(u"label_23")
        self.label_23.setGeometry(QRect(250, 140, 111, 31))
        self.label_23.setStyleSheet(u"")
        self.label_24 = QLabel(self.groupBox_4)
        self.label_24.setObjectName(u"label_24")
        self.label_24.setGeometry(QRect(20, 270, 591, 41))
        self.label_24.setStyleSheet(u"")
        self.pushButton_18 = QPushButton(self.groupBox_4)
        self.pushButton_18.setObjectName(u"pushButton_18")
        self.pushButton_18.setGeometry(QRect(550, 370, 80, 20))
        self.stackedWidget.addWidget(self.page_3)
        self.page_4 = QWidget()
        self.page_4.setObjectName(u"page_4")
        self.groupBox_5 = QGroupBox(self.page_4)
        self.groupBox_5.setObjectName(u"groupBox_5")
        self.groupBox_5.setGeometry(QRect(10, 0, 651, 401))
        self.widget_5 = QWidget(self.groupBox_5)
        self.widget_5.setObjectName(u"widget_5")
        self.widget_5.setGeometry(QRect(10, 20, 151, 171))
        self.widget_5.setAutoFillBackground(False)
        self.widget_5.setStyleSheet(u"image: url(:/pics/files/category/Beauty and the Beast (Classic Reprint).jpg);\n"
"")
        self.label_25 = QLabel(self.groupBox_5)
        self.label_25.setObjectName(u"label_25")
        self.label_25.setGeometry(QRect(20, 210, 141, 21))
        self.pushButton_5 = QPushButton(self.groupBox_5)
        self.pushButton_5.setObjectName(u"pushButton_5")
        self.pushButton_5.setGeometry(QRect(250, 190, 381, 41))
        self.pushButton_5.setStyleSheet(u"background-color: rgb(85, 0, 127);\n"
"")
        self.pushButton_5.setIcon(icon)
        self.label_26 = QLabel(self.groupBox_5)
        self.label_26.setObjectName(u"label_26")
        self.label_26.setGeometry(QRect(250, 40, 241, 21))
        self.label_26.setStyleSheet(u"")
        self.label_27 = QLabel(self.groupBox_5)
        self.label_27.setObjectName(u"label_27")
        self.label_27.setGeometry(QRect(250, 80, 161, 21))
        self.label_27.setStyleSheet(u"")
        self.label_28 = QLabel(self.groupBox_5)
        self.label_28.setObjectName(u"label_28")
        self.label_28.setGeometry(QRect(250, 110, 251, 21))
        self.label_28.setStyleSheet(u"")
        self.label_29 = QLabel(self.groupBox_5)
        self.label_29.setObjectName(u"label_29")
        self.label_29.setGeometry(QRect(250, 140, 111, 31))
        self.label_29.setStyleSheet(u"")
        self.label_30 = QLabel(self.groupBox_5)
        self.label_30.setObjectName(u"label_30")
        self.label_30.setGeometry(QRect(20, 270, 591, 41))
        self.label_30.setStyleSheet(u"")
        self.pushButton_19 = QPushButton(self.groupBox_5)
        self.pushButton_19.setObjectName(u"pushButton_19")
        self.pushButton_19.setGeometry(QRect(550, 370, 80, 20))
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QWidget()
        self.page_5.setObjectName(u"page_5")
        self.groupBox_6 = QGroupBox(self.page_5)
        self.groupBox_6.setObjectName(u"groupBox_6")
        self.groupBox_6.setGeometry(QRect(10, 0, 651, 401))
        self.widget_6 = QWidget(self.groupBox_6)
        self.widget_6.setObjectName(u"widget_6")
        self.widget_6.setGeometry(QRect(10, 20, 151, 171))
        self.widget_6.setAutoFillBackground(False)
        self.widget_6.setStyleSheet(u"image: url(:/pics/files/coverpage/b201806081528456239.jpg);")
        self.label_31 = QLabel(self.groupBox_6)
        self.label_31.setObjectName(u"label_31")
        self.label_31.setGeometry(QRect(20, 210, 141, 21))
        self.pushButton_6 = QPushButton(self.groupBox_6)
        self.pushButton_6.setObjectName(u"pushButton_6")
        self.pushButton_6.setGeometry(QRect(250, 190, 381, 41))
        self.pushButton_6.setStyleSheet(u"background-color: rgb(85, 0, 127);\n"
"")
        self.pushButton_6.setIcon(icon)
        self.label_32 = QLabel(self.groupBox_6)
        self.label_32.setObjectName(u"label_32")
        self.label_32.setGeometry(QRect(250, 40, 241, 21))
        self.label_32.setStyleSheet(u"")
        self.label_33 = QLabel(self.groupBox_6)
        self.label_33.setObjectName(u"label_33")
        self.label_33.setGeometry(QRect(250, 80, 131, 21))
        self.label_33.setStyleSheet(u"")
        self.label_34 = QLabel(self.groupBox_6)
        self.label_34.setObjectName(u"label_34")
        self.label_34.setGeometry(QRect(250, 110, 251, 21))
        self.label_34.setStyleSheet(u"")
        self.label_35 = QLabel(self.groupBox_6)
        self.label_35.setObjectName(u"label_35")
        self.label_35.setGeometry(QRect(250, 140, 111, 31))
        self.label_35.setStyleSheet(u"")
        self.label_36 = QLabel(self.groupBox_6)
        self.label_36.setObjectName(u"label_36")
        self.label_36.setGeometry(QRect(20, 270, 591, 41))
        self.label_36.setStyleSheet(u"")
        self.pushButton_20 = QPushButton(self.groupBox_6)
        self.pushButton_20.setObjectName(u"pushButton_20")
        self.pushButton_20.setGeometry(QRect(550, 370, 80, 20))
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QWidget()
        self.page_6.setObjectName(u"page_6")
        self.groupBox_7 = QGroupBox(self.page_6)
        self.groupBox_7.setObjectName(u"groupBox_7")
        self.groupBox_7.setGeometry(QRect(10, 0, 651, 401))
        self.widget_7 = QWidget(self.groupBox_7)
        self.widget_7.setObjectName(u"widget_7")
        self.widget_7.setGeometry(QRect(10, 20, 151, 171))
        self.widget_7.setAutoFillBackground(False)
        self.widget_7.setStyleSheet(u"image: url(:/pics/files/coverpage/5117CIwLSFL._SX331_BO1204203200_.jpg);")
        self.label_37 = QLabel(self.groupBox_7)
        self.label_37.setObjectName(u"label_37")
        self.label_37.setGeometry(QRect(20, 210, 141, 21))
        self.pushButton_7 = QPushButton(self.groupBox_7)
        self.pushButton_7.setObjectName(u"pushButton_7")
        self.pushButton_7.setGeometry(QRect(250, 190, 381, 41))
        self.pushButton_7.setStyleSheet(u"background-color: rgb(85, 0, 127);\n"
"")
        self.pushButton_7.setIcon(icon)
        self.label_38 = QLabel(self.groupBox_7)
        self.label_38.setObjectName(u"label_38")
        self.label_38.setGeometry(QRect(250, 40, 241, 21))
        self.label_38.setStyleSheet(u"")
        self.label_39 = QLabel(self.groupBox_7)
        self.label_39.setObjectName(u"label_39")
        self.label_39.setGeometry(QRect(250, 80, 131, 21))
        self.label_39.setStyleSheet(u"")
        self.label_40 = QLabel(self.groupBox_7)
        self.label_40.setObjectName(u"label_40")
        self.label_40.setGeometry(QRect(250, 110, 251, 21))
        self.label_40.setStyleSheet(u"")
        self.label_41 = QLabel(self.groupBox_7)
        self.label_41.setObjectName(u"label_41")
        self.label_41.setGeometry(QRect(250, 140, 111, 31))
        self.label_41.setStyleSheet(u"")
        self.label_42 = QLabel(self.groupBox_7)
        self.label_42.setObjectName(u"label_42")
        self.label_42.setGeometry(QRect(20, 270, 591, 41))
        self.label_42.setStyleSheet(u"")
        self.pushButton_21 = QPushButton(self.groupBox_7)
        self.pushButton_21.setObjectName(u"pushButton_21")
        self.pushButton_21.setGeometry(QRect(550, 370, 80, 20))
        self.stackedWidget.addWidget(self.page_6)
        self.page_7 = QWidget()
        self.page_7.setObjectName(u"page_7")
        self.groupBox_8 = QGroupBox(self.page_7)
        self.groupBox_8.setObjectName(u"groupBox_8")
        self.groupBox_8.setGeometry(QRect(10, 10, 651, 401))
        self.widget_8 = QWidget(self.groupBox_8)
        self.widget_8.setObjectName(u"widget_8")
        self.widget_8.setGeometry(QRect(10, 20, 151, 171))
        self.widget_8.setAutoFillBackground(False)
        self.widget_8.setStyleSheet(u"image: url(:/pics/files/coverpage/b201806111528741778.jpg);\n"
"")
        self.label_43 = QLabel(self.groupBox_8)
        self.label_43.setObjectName(u"label_43")
        self.label_43.setGeometry(QRect(20, 210, 141, 21))
        self.pushButton_8 = QPushButton(self.groupBox_8)
        self.pushButton_8.setObjectName(u"pushButton_8")
        self.pushButton_8.setGeometry(QRect(250, 190, 381, 41))
        self.pushButton_8.setStyleSheet(u"background-color: rgb(85, 0, 127);\n"
"")
        self.pushButton_8.setIcon(icon)
        self.label_44 = QLabel(self.groupBox_8)
        self.label_44.setObjectName(u"label_44")
        self.label_44.setGeometry(QRect(250, 40, 241, 21))
        self.label_44.setStyleSheet(u"")
        self.label_45 = QLabel(self.groupBox_8)
        self.label_45.setObjectName(u"label_45")
        self.label_45.setGeometry(QRect(250, 80, 131, 21))
        self.label_45.setStyleSheet(u"")
        self.label_46 = QLabel(self.groupBox_8)
        self.label_46.setObjectName(u"label_46")
        self.label_46.setGeometry(QRect(250, 110, 251, 21))
        self.label_46.setStyleSheet(u"")
        self.label_47 = QLabel(self.groupBox_8)
        self.label_47.setObjectName(u"label_47")
        self.label_47.setGeometry(QRect(250, 140, 111, 31))
        self.label_47.setStyleSheet(u"")
        self.label_48 = QLabel(self.groupBox_8)
        self.label_48.setObjectName(u"label_48")
        self.label_48.setGeometry(QRect(20, 270, 591, 41))
        self.label_48.setStyleSheet(u"")
        self.pushButton_22 = QPushButton(self.groupBox_8)
        self.pushButton_22.setObjectName(u"pushButton_22")
        self.pushButton_22.setGeometry(QRect(550, 370, 80, 20))
        self.stackedWidget.addWidget(self.page_7)
        self.page_8 = QWidget()
        self.page_8.setObjectName(u"page_8")
        self.groupBox_9 = QGroupBox(self.page_8)
        self.groupBox_9.setObjectName(u"groupBox_9")
        self.groupBox_9.setGeometry(QRect(10, 0, 651, 401))
        self.widget_9 = QWidget(self.groupBox_9)
        self.widget_9.setObjectName(u"widget_9")
        self.widget_9.setGeometry(QRect(10, 20, 151, 171))
        self.widget_9.setAutoFillBackground(False)
        self.widget_9.setStyleSheet(u"image: url(:/pics/files/coverpage/513e7BP39PL._SX330_BO1204203200_.jpg);\n"
"")
        self.label_49 = QLabel(self.groupBox_9)
        self.label_49.setObjectName(u"label_49")
        self.label_49.setGeometry(QRect(20, 210, 141, 21))
        self.pushButton_9 = QPushButton(self.groupBox_9)
        self.pushButton_9.setObjectName(u"pushButton_9")
        self.pushButton_9.setGeometry(QRect(250, 190, 381, 41))
        self.pushButton_9.setStyleSheet(u"background-color: rgb(85, 0, 127);\n"
"")
        self.pushButton_9.setIcon(icon)
        self.label_50 = QLabel(self.groupBox_9)
        self.label_50.setObjectName(u"label_50")
        self.label_50.setGeometry(QRect(250, 40, 241, 21))
        self.label_50.setStyleSheet(u"")
        self.label_51 = QLabel(self.groupBox_9)
        self.label_51.setObjectName(u"label_51")
        self.label_51.setGeometry(QRect(250, 80, 131, 21))
        self.label_51.setStyleSheet(u"")
        self.label_52 = QLabel(self.groupBox_9)
        self.label_52.setObjectName(u"label_52")
        self.label_52.setGeometry(QRect(250, 110, 251, 21))
        self.label_52.setStyleSheet(u"")
        self.label_53 = QLabel(self.groupBox_9)
        self.label_53.setObjectName(u"label_53")
        self.label_53.setGeometry(QRect(250, 140, 111, 31))
        self.label_53.setStyleSheet(u"")
        self.label_54 = QLabel(self.groupBox_9)
        self.label_54.setObjectName(u"label_54")
        self.label_54.setGeometry(QRect(20, 270, 591, 41))
        self.label_54.setStyleSheet(u"")
        self.pushButton_23 = QPushButton(self.groupBox_9)
        self.pushButton_23.setObjectName(u"pushButton_23")
        self.pushButton_23.setGeometry(QRect(550, 370, 80, 20))
        self.stackedWidget.addWidget(self.page_8)
        self.page_9 = QWidget()
        self.page_9.setObjectName(u"page_9")
        self.groupBox_10 = QGroupBox(self.page_9)
        self.groupBox_10.setObjectName(u"groupBox_10")
        self.groupBox_10.setGeometry(QRect(10, 10, 651, 401))
        self.widget_10 = QWidget(self.groupBox_10)
        self.widget_10.setObjectName(u"widget_10")
        self.widget_10.setGeometry(QRect(10, 20, 151, 171))
        self.widget_10.setAutoFillBackground(False)
        self.widget_10.setStyleSheet(u"image: url(:/pics/files/coverpage/41UwqWhI4L._SX329_BO1204203200_.jpg);\n"
"")
        self.label_55 = QLabel(self.groupBox_10)
        self.label_55.setObjectName(u"label_55")
        self.label_55.setGeometry(QRect(20, 210, 141, 21))
        self.pushButton_10 = QPushButton(self.groupBox_10)
        self.pushButton_10.setObjectName(u"pushButton_10")
        self.pushButton_10.setGeometry(QRect(250, 190, 381, 41))
        self.pushButton_10.setStyleSheet(u"background-color: rgb(85, 0, 127);\n"
"")
        self.pushButton_10.setIcon(icon)
        self.label_56 = QLabel(self.groupBox_10)
        self.label_56.setObjectName(u"label_56")
        self.label_56.setGeometry(QRect(250, 40, 241, 21))
        self.label_56.setStyleSheet(u"")
        self.label_57 = QLabel(self.groupBox_10)
        self.label_57.setObjectName(u"label_57")
        self.label_57.setGeometry(QRect(250, 80, 161, 21))
        self.label_57.setStyleSheet(u"")
        self.label_58 = QLabel(self.groupBox_10)
        self.label_58.setObjectName(u"label_58")
        self.label_58.setGeometry(QRect(250, 110, 251, 21))
        self.label_58.setStyleSheet(u"")
        self.label_59 = QLabel(self.groupBox_10)
        self.label_59.setObjectName(u"label_59")
        self.label_59.setGeometry(QRect(250, 140, 111, 31))
        self.label_59.setStyleSheet(u"")
        self.label_60 = QLabel(self.groupBox_10)
        self.label_60.setObjectName(u"label_60")
        self.label_60.setGeometry(QRect(20, 270, 591, 41))
        self.label_60.setStyleSheet(u"")
        self.pushButton_24 = QPushButton(self.groupBox_10)
        self.pushButton_24.setObjectName(u"pushButton_24")
        self.pushButton_24.setGeometry(QRect(550, 370, 80, 20))
        self.stackedWidget.addWidget(self.page_9)

        self.retranslateUi(bookdetails1)

        self.stackedWidget.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(bookdetails1)
    # setupUi

    def retranslateUi(self, bookdetails1):
        bookdetails1.setWindowTitle(QCoreApplication.translate("bookdetails1", u"Dialog", None))
        self.groupBox.setTitle(QCoreApplication.translate("bookdetails1", u"GroupBox", None))
        self.label_2.setText(QCoreApplication.translate("bookdetails1", u"O.O.Programming C++", None))
        self.pushButton.setText("")
        self.label.setText(QCoreApplication.translate("bookdetails1", u"Title:Object Oriented Programming C++", None))
        self.label_3.setText(QCoreApplication.translate("bookdetails1", u"Author : B Chandra", None))
        self.label_4.setText(QCoreApplication.translate("bookdetails1", u"Gendre : Academics", None))
        self.label_5.setText(QCoreApplication.translate("bookdetails1", u"Price: 3000 XAF", None))
        self.label_6.setText(QCoreApplication.translate("bookdetails1", u"Description: ", None))
        self.pushButton_15.setText(QCoreApplication.translate("bookdetails1", u"Back", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("bookdetails1", u"GroupBox", None))
        self.label_7.setText(QCoreApplication.translate("bookdetails1", u"BatMan Comics", None))
        self.pushButton_2.setText("")
        self.label_8.setText(QCoreApplication.translate("bookdetails1", u"Title: BatMan Comics", None))
        self.label_9.setText(QCoreApplication.translate("bookdetails1", u"Author: Neal Adams", None))
        self.label_10.setText(QCoreApplication.translate("bookdetails1", u"Gendre :  Comics", None))
        self.label_11.setText(QCoreApplication.translate("bookdetails1", u"Price: 4000 XAF", None))
        self.label_12.setText(QCoreApplication.translate("bookdetails1", u"Description:", None))
        self.pushButton_16.setText(QCoreApplication.translate("bookdetails1", u"Back", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("bookdetails1", u"GroupBox", None))
        self.label_13.setText(QCoreApplication.translate("bookdetails1", u"Art Matters", None))
        self.pushButton_3.setText("")
        self.label_14.setText(QCoreApplication.translate("bookdetails1", u"Title:Art Matters", None))
        self.label_15.setText(QCoreApplication.translate("bookdetails1", u"Author : Artews Didi", None))
        self.label_16.setText(QCoreApplication.translate("bookdetails1", u"Gendre : Classic", None))
        self.label_17.setText(QCoreApplication.translate("bookdetails1", u"Price: 3000 XAF", None))
        self.label_18.setText(QCoreApplication.translate("bookdetails1", u"Description:", None))
        self.pushButton_17.setText(QCoreApplication.translate("bookdetails1", u"Back", None))
        self.groupBox_4.setTitle(QCoreApplication.translate("bookdetails1", u"GroupBox", None))
        self.label_19.setText(QCoreApplication.translate("bookdetails1", u"Atomic Habits", None))
        self.pushButton_4.setText("")
        self.label_20.setText(QCoreApplication.translate("bookdetails1", u"title: Atomic Habit", None))
        self.label_21.setText(QCoreApplication.translate("bookdetails1", u"Author : James Clear", None))
        self.label_22.setText(QCoreApplication.translate("bookdetails1", u"Gendre : Selfhelp", None))
        self.label_23.setText(QCoreApplication.translate("bookdetails1", u"Price: 3000 XAF", None))
        self.label_24.setText(QCoreApplication.translate("bookdetails1", u"Description:", None))
        self.pushButton_18.setText(QCoreApplication.translate("bookdetails1", u"Back", None))
        self.groupBox_5.setTitle(QCoreApplication.translate("bookdetails1", u"GroupBox", None))
        self.label_25.setText(QCoreApplication.translate("bookdetails1", u"Beauty and Beast", None))
        self.pushButton_5.setText("")
        self.label_26.setText(QCoreApplication.translate("bookdetails1", u"Title: Beauty and Beast", None))
        self.label_27.setText(QCoreApplication.translate("bookdetails1", u"Author : Charmes Lamb", None))
        self.label_28.setText(QCoreApplication.translate("bookdetails1", u"Gendre : Classic", None))
        self.label_29.setText(QCoreApplication.translate("bookdetails1", u"Price: 3000 XAF", None))
        self.label_30.setText(QCoreApplication.translate("bookdetails1", u"Description:", None))
        self.pushButton_19.setText(QCoreApplication.translate("bookdetails1", u"Back", None))
        self.groupBox_6.setTitle(QCoreApplication.translate("bookdetails1", u"GroupBox", None))
        self.label_31.setText(QCoreApplication.translate("bookdetails1", u"Discrete Mahematics", None))
        self.pushButton_6.setText("")
        self.label_32.setText(QCoreApplication.translate("bookdetails1", u"Discrete Mathematics", None))
        self.label_33.setText(QCoreApplication.translate("bookdetails1", u"Author : OOP", None))
        self.label_34.setText(QCoreApplication.translate("bookdetails1", u"Gendre : Academics", None))
        self.label_35.setText(QCoreApplication.translate("bookdetails1", u"Price: 3000 XAF", None))
        self.label_36.setText(QCoreApplication.translate("bookdetails1", u"Description:", None))
        self.pushButton_20.setText(QCoreApplication.translate("bookdetails1", u"Back", None))
        self.groupBox_7.setTitle(QCoreApplication.translate("bookdetails1", u"GroupBox", None))
        self.label_37.setText(QCoreApplication.translate("bookdetails1", u"Money and Wealth", None))
        self.pushButton_7.setText("")
        self.label_38.setText(QCoreApplication.translate("bookdetails1", u"Title: Money and Wealth", None))
        self.label_39.setText(QCoreApplication.translate("bookdetails1", u"Author : Raid Ernest", None))
        self.label_40.setText(QCoreApplication.translate("bookdetails1", u"Gendre : Money", None))
        self.label_41.setText(QCoreApplication.translate("bookdetails1", u"Price: 3000 XAF", None))
        self.label_42.setText(QCoreApplication.translate("bookdetails1", u"Description:", None))
        self.pushButton_21.setText(QCoreApplication.translate("bookdetails1", u"Back", None))
        self.groupBox_8.setTitle(QCoreApplication.translate("bookdetails1", u"GroupBox", None))
        self.label_43.setText(QCoreApplication.translate("bookdetails1", u"Think Python", None))
        self.pushButton_8.setText("")
        self.label_44.setText(QCoreApplication.translate("bookdetails1", u"Title: Think Python", None))
        self.label_45.setText(QCoreApplication.translate("bookdetails1", u"Author : Joe Aqwe", None))
        self.label_46.setText(QCoreApplication.translate("bookdetails1", u"Gendre : Academics", None))
        self.label_47.setText(QCoreApplication.translate("bookdetails1", u"Price: 3000 XAF", None))
        self.label_48.setText(QCoreApplication.translate("bookdetails1", u"Description:", None))
        self.pushButton_22.setText(QCoreApplication.translate("bookdetails1", u"Back", None))
        self.groupBox_9.setTitle(QCoreApplication.translate("bookdetails1", u"GroupBox", None))
        self.label_49.setText(QCoreApplication.translate("bookdetails1", u"Intelligent Investor", None))
        self.pushButton_9.setText("")
        self.label_50.setText(QCoreApplication.translate("bookdetails1", u"Title: Inteligent Investor", None))
        self.label_51.setText(QCoreApplication.translate("bookdetails1", u"Author : B Chandra", None))
        self.label_52.setText(QCoreApplication.translate("bookdetails1", u"Gendre : Money", None))
        self.label_53.setText(QCoreApplication.translate("bookdetails1", u"Price: 3000 XAF", None))
        self.label_54.setText(QCoreApplication.translate("bookdetails1", u"Description:", None))
        self.pushButton_23.setText(QCoreApplication.translate("bookdetails1", u"Back", None))
        self.groupBox_10.setTitle(QCoreApplication.translate("bookdetails1", u"GroupBox", None))
        self.label_55.setText(QCoreApplication.translate("bookdetails1", u"Power of Zero", None))
        self.pushButton_10.setText("")
        self.label_56.setText(QCoreApplication.translate("bookdetails1", u"Title: Power of Zero", None))
        self.label_57.setText(QCoreApplication.translate("bookdetails1", u"Author: David Mcknight", None))
        self.label_58.setText(QCoreApplication.translate("bookdetails1", u"Gendre : Selfhelp", None))
        self.label_59.setText(QCoreApplication.translate("bookdetails1", u"Price: 3000 XAF", None))
        self.label_60.setText(QCoreApplication.translate("bookdetails1", u"Description:", None))
        self.pushButton_24.setText(QCoreApplication.translate("bookdetails1", u"Back", None))
          # retranslateUi
       